# Generated by Django 5.2.15 on 2026-08-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_dashboard", "0005_threaded_support_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="origin_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="platform",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
