# Generated by Django 5.0.1 on 2026-05-02 19:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("donor_name", models.CharField(max_length=150)),
                ("donor_email", models.EmailField(db_index=True, max_length=254)),
                ("amount", models.IntegerField(help_text="Amount in cents (e.g. 1000 = $10.00).")),
                ("currency", models.CharField(default="usd", max_length=3)),
                (
                    "type",
                    models.CharField(
                        choices=[("one_time", "One-time"), ("monthly", "Monthly")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "stripe_payment_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stripe PaymentIntent ID (one-time) or SetupIntent ID (monthly).",
                        max_length=255,
                    ),
                ),
                ("stripe_customer_id", models.CharField(blank=True, db_index=True, max_length=255)),
                (
                    "is_early_supporter",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True for the first 1,000 successful donors.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "donations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("stripe_price_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("past_due", "Past Due"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("billing_cycle_anchor", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "donation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="donations.donation",
                    ),
                ),
            ],
            options={
                "db_table": "donations_subscriptions",
            },
        ),
    ]
