# Generated by Django 5.2.15 on 2026-06-21 15:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeWebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_event_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("event_type", models.CharField(db_index=True, max_length=255)),
                (
                    "api_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("livemode", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("processing_error", models.TextField(blank=True, default="")),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "stripe_webhook_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupporterProgramState",
            fields=[
                (
                    "key",
                    models.CharField(
                        default="global",
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("next_early_supporter_number", models.PositiveIntegerField(default=1)),
                (
                    "assigned_early_supporter_count",
                    models.PositiveIntegerField(default=0),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "supporter_program_state",
            },
        ),
        migrations.CreateModel(
            name="SupportPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("initial", "Initial"),
                            ("recurring", "Recurring"),
                            ("refund", "Refund"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(default="usd", max_length=8)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                (
                    "stripe_invoice_id",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "failure_code",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("failure_message", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "support_payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="donation",
            name="checkout_session_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="checkout_url",
            field=models.URLField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="donation",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="expired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="idempotency_key",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="donation",
            name="last_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="donation",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="donation",
            name="source",
            field=models.CharField(
                choices=[
                    ("hosted_checkout", "Hosted checkout"),
                    ("graphql_legacy", "Legacy GraphQL"),
                ],
                db_index=True,
                default="hosted_checkout",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="donation",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="donation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_donations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscription",
            name="cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="currency",
            field=models.CharField(default="usd", max_length=8),
        ),
        migrations.AddField(
            model_name="subscription",
            name="current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="current_period_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_customer_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="amount",
            field=models.PositiveIntegerField(
                help_text="Amount in cents (for example 1000 = 10.00 USD)."
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="currency",
            field=models.CharField(default="usd", max_length=8),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donor_email",
            field=models.EmailField(blank=True, db_index=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donor_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="donation",
            name="is_early_supporter",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="stripe_customer_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="donation",
            name="stripe_payment_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Legacy Stripe identifier kept for backward compatibility.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="type",
            field=models.CharField(
                choices=[("one_time", "One-time"), ("monthly", "Monthly")],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("incomplete", "Incomplete"),
                    ("active", "Active"),
                    ("trialing", "Trialing"),
                    ("past_due", "Past due"),
                    ("unpaid", "Unpaid"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="incomplete",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="stripe_price_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="SupporterIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "normalized_email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "is_early_supporter",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "early_supporter_number",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("first_supported_at", models.DateTimeField(blank=True, null=True)),
                ("last_supported_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supporter_identity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "supporter_identities",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="donation",
            name="supporter_identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donations",
                to="donations.supporteridentity",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="supporter_identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="donations.supporteridentity",
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["supporter_identity", "created_at"],
                name="idx_donation_identity_created",
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["user", "status"], name="idx_donation_user_status"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["user", "status"], name="idx_subscription_user_status"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["supporter_identity", "status"], name="idx_sub_identity_status"
            ),
        ),
        migrations.AddField(
            model_name="supportpayment",
            name="donation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="donations.donation",
            ),
        ),
        migrations.AddField(
            model_name="supportpayment",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="donations.subscription",
            ),
        ),
        migrations.AddField(
            model_name="supportpayment",
            name="supporter_identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="donations.supporteridentity",
            ),
        ),
        migrations.AddField(
            model_name="supportpayment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="supportpayment",
            index=models.Index(fields=["subscription", "created_at"], name="idx_pay_sub_created"),
        ),
        migrations.AddIndex(
            model_name="supportpayment",
            index=models.Index(
                fields=["supporter_identity", "status"], name="idx_pay_identity_status"
            ),
        ),
    ]
