# Generated by Django 5.0.1 on 2026-02-27 18:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "post_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video"), ("text", "Text")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("caption", models.TextField(blank=True, max_length=2200, null=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("love", "Love"),
                            ("trust", "Trust"),
                            ("worship", "Worship"),
                            ("patience", "Patience"),
                            ("prayer", "Prayer"),
                        ],
                        db_index=True,
                        max_length=50,
                        null=True,
                    ),
                ),
                ("media_count", models.IntegerField(default=0)),
                ("view_count", models.IntegerField(default=0)),
                ("is_mature_content", models.BooleanField(default=False)),
                ("scripture_book", models.CharField(blank=True, max_length=50, null=True)),
                ("scripture_chapter", models.IntegerField(blank=True, null=True)),
                ("scripture_verse_start", models.IntegerField(blank=True, null=True)),
                ("scripture_verse_end", models.IntegerField(blank=True, null=True)),
                ("scripture_version", models.CharField(default="KJV", max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("media_url", models.URLField(max_length=500)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=20
                    ),
                ),
                ("thumbnail_url", models.URLField(blank=True, max_length=500, null=True)),
                ("order", models.IntegerField(default=0)),
                ("width", models.IntegerField(default=0)),
                ("height", models.IntegerField(default=0)),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, help_text="Video duration in seconds", null=True
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_media",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "db_table": "post_media",
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["user", "-created_at"], name="idx_post_user_created"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["category"], name="idx_post_category"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["deleted_at"], name="idx_post_deleted"),
        ),
        migrations.AddIndex(
            model_name="postmedia",
            index=models.Index(fields=["post", "order"], name="idx_postmedia_post_order"),
        ),
        migrations.AddConstraint(
            model_name="postmedia",
            constraint=models.UniqueConstraint(
                fields=("post", "order"), name="uq_postmedia_post_order"
            ),
        ),
    ]
