# Generated by Django 5.0.1 on 2026-03-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0001_initial"),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="media_files",
            field=models.ManyToManyField(
                blank=True,
                help_text="Attached media files via uploadMedia",
                related_name="posts",
                to="media.mediafile",
            ),
        ),
    ]
