# Generated by Django 5.0.1 on 2026-03-06 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("engagement", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmarkfolder",
            name="icon",
        ),
    ]
