# Generated by Django 5.0.1 on 2026-03-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.CharField(max_length=50, primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("icon", models.URLField(max_length=500)),
                ("bg_color", models.CharField(max_length=7)),
                ("bd_color", models.CharField(max_length=7)),
                ("order", models.IntegerField()),
            ],
            options={
                "db_table": "categories",
                "ordering": ["order"],
            },
        ),
    ]
