# Generated by Django 5.0.1 on 2026-03-21 13:08

from django.db import migrations


def seed_categories(apps, schema_editor):
    Category = apps.get_model("categories", "Category")
    discover_categories = [
        {
            "id": "1",
            "label": "All",
            "slug": "all",
            "icon": "https://storage.googleapis.com/ziona-media-dev/categories/images/all.png",
            "bg_color": "#F3F2D8",
            "bd_color": "#CAC653",
            "order": 1,
        },
        {
            "id": "2",
            "label": "Love",
            "slug": "love",
            "icon": "https://storage.googleapis.com/ziona-media-dev/categories/images/love.png",
            "bg_color": "#F3D8DA",
            "bd_color": "#C8545D",
            "order": 2,
        },
        {
            "id": "3",
            "label": "Trust",
            "slug": "trust",
            "icon": "https://storage.googleapis.com/ziona-media-dev/categories/images/trust.png",
            "bg_color": "#D8DBF3",
            "bd_color": "#292E62",
            "order": 3,
        },
        {
            "id": "4",
            "label": "Worship",
            "slug": "worship",
            "icon": "https://storage.googleapis.com/ziona-media-dev/categories/images/worship.png",
            "bg_color": "#F3E8D8",
            "bd_color": "#C89854",
            "order": 4,
        },
        {
            "id": "5",
            "label": "Patience",
            "slug": "patience",
            "icon": "https://storage.googleapis.com/ziona-media-dev/categories/images/patience.png",
            "bg_color": "#F3D8EB",
            "bd_color": "#682253",
            "order": 5,
        },
        {
            "id": "6",
            "label": "Prayer",
            "slug": "prayer",
            "icon": "https://storage.googleapis.com/ziona-media-dev/categories/images/prayer.png",
            "bg_color": "#D8F3EC",
            "bd_color": "#226858",
            "order": 6,
        },
    ]
    for cat in discover_categories:
        Category.objects.update_or_create(id=cat["id"], defaults=cat)


def reverse_seed(apps, schema_editor):
    Category = apps.get_model("categories", "Category")
    Category.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_seed),
    ]
