# Generated by Django 5.0.1 on 2026-03-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_seed_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="text_post_bg",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
