# Generated by Django 5.0.1 on 2026-02-14 14:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, null=True, unique=True
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=150)),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("avatar_url", models.URLField(blank=True, max_length=500)),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("admin", "Admin")],
                        db_index=True,
                        default="user",
                        max_length=10,
                    ),
                ),
                ("is_email_verified", models.BooleanField(default=False)),
                ("encrypted_dob", models.BinaryField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "auth_provider",
                    models.CharField(
                        choices=[("email", "Email"), ("google", "Google")],
                        default="email",
                        max_length=20,
                    ),
                ),
                (
                    "firebase_uid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "users",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="idx_user_email"),
                    models.Index(fields=["username"], name="idx_user_username"),
                    models.Index(fields=["firebase_uid"], name="idx_user_firebase_uid"),
                ],
            },
        ),
    ]
