# Generated by Django 5.0.1 on 2026-02-27 13:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "interest",
                    models.CharField(
                        choices=[
                            ("love", "Love"),
                            ("trust", "Trust"),
                            ("worship", "Worship"),
                            ("patience", "Patience"),
                            ("prayer", "Prayer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_interests",
                "indexes": [models.Index(fields=["user"], name="idx_userinterest_user")],
            },
        ),
        migrations.AddConstraint(
            model_name="userinterest",
            constraint=models.UniqueConstraint(
                fields=("user", "interest"), name="uq_user_interest"
            ),
        ),
    ]
