# Generated by Django 5.0.1 on 2026-03-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userinterest_userinterest_uq_user_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_name_change",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_username_change",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
