# Generated by Django 5.0.1 on 2026-03-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_last_name_change_user_last_username_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="needs_username_selection",
            field=models.BooleanField(default=False),
        ),
    ]
