# Generated by Django 5.0.1 on 2026-03-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_needs_username_selection"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="social_auth_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "Email/Password"),
                    ("google", "Google"),
                    ("facebook", "Facebook"),
                    ("apple", "Apple"),
                ],
                help_text="How the user originally registered. Null = email/password",
                max_length=20,
                null=True,
            ),
        ),
    ]
