# Generated by Django 5.0.1 on 2026-04-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_google_id_user_social_auth_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("warned", "Warned"), ("suspended", "Suspended")],
                db_index=True,
                default="active",
                help_text="Admin-managed moderation status. Separate from Django is_active.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="suspension_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="warned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
