# Generated by Django 5.0.1 on 2026-04-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_status_user_suspended_at_user_suspension_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hide_like_count",
            field=models.BooleanField(default=False),
        ),
    ]
