# Generated by Django 5.0.1 on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_hide_like_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("google", "Google"),
                    ("apple", "Apple"),
                ],
                default="email",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="apple_sub",
            field=models.CharField(
                blank=True,
                help_text="Stable Sign in with Apple subject claim for this developer team.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
