# Generated by Django 5.2.15 on 2026-06-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_apple_sub"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio_link",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
