# Generated by Django 5.2.15 on 2026-06-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_user_bio_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token_invalid_before",
            field=models.DateTimeField(
                blank=True,
                help_text="Access tokens issued before this timestamp are rejected on sensitive flows.",
                null=True,
            ),
        ),
    ]
