# Generated by Django 5.2.17 on 2026-10-02 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_creator_search_trigram_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDailyActivity",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_activity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_daily_activity",
                "indexes": [models.Index(fields=["date"], name="idx_user_daily_activity_date")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"), name="uniq_user_daily_activity"
                    )
                ],
            },
        ),
    ]
