# Generated by Django 5.0.1 on 2026-05-02 19:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppStoreLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android")], max_length=10, unique=True
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "landing_app_store_links",
            },
        ),
        migrations.CreateModel(
            name="CompanyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("value", models.IntegerField(default=0)),
                (
                    "display_value",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable display string, e.g. '2,123+' or '10k+'.",
                        max_length=50,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "landing_company_stats",
            },
        ),
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("privacy_policy", "Privacy Policy"),
                            ("terms_of_service", "Terms of Service"),
                            ("community_guidelines", "Community Guidelines"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("content", models.TextField(help_text="Markdown content.")),
                ("version", models.CharField(max_length=20)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "landing_legal_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[("ZIONA", "Ziona"), ("ZIONKING", "Zion King")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("source", models.CharField(default="landing_page", max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("confirmed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "landing_waitlist_entries",
            },
        ),
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[("ZIONA", "Ziona"), ("ZIONKING", "Zion King")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=10,
                    ),
                ),
                ("honeypot", models.CharField(blank=True, default="", max_length=200)),
                ("is_spam", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "landing_contact_submissions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["brand", "status"], name="idx_contact_brand_status")
                ],
            },
        ),
        migrations.CreateModel(
            name="LegalAcceptance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_acceptances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "landing_legal_acceptances",
            },
        ),
        migrations.AddConstraint(
            model_name="legaldocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("type",),
                name="uq_active_legal_doc_per_type",
            ),
        ),
        migrations.AddField(
            model_name="legalacceptance",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="acceptances",
                to="landing.legaldocument",
            ),
        ),
        migrations.AddIndex(
            model_name="waitlistentry",
            index=models.Index(fields=["brand", "created_at"], name="idx_waitlist_brand_created"),
        ),
        migrations.AddConstraint(
            model_name="waitlistentry",
            constraint=models.UniqueConstraint(
                fields=("brand", "email"), name="uq_waitlist_brand_email"
            ),
        ),
        migrations.AddConstraint(
            model_name="legalacceptance",
            constraint=models.UniqueConstraint(
                fields=("user", "document"), name="uq_user_legal_acceptance"
            ),
        ),
    ]
