# Generated by Django 5.0.1 on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legaldocument",
            name="content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional text fallback. Mobile should render document_url.",
            ),
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="document_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Public URL for the canonical legal document file.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="document_type",
            field=models.CharField(
                blank=True,
                default="application/pdf",
                help_text="MIME type for document_url, e.g. application/pdf.",
                max_length=100,
            ),
        ),
    ]
