# Generated by Django 5.0.1 on 2026-03-16 20:03

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CircleRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("rule_number", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("is_default", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "circle_rules",
                "ordering": ["rule_number"],
            },
        ),
        migrations.CreateModel(
            name="Circle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, validators=[django.core.validators.MinLengthValidator(3)]
                    ),
                ),
                ("description", models.TextField()),
                ("cover_image", models.URLField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_circles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "circles",
            },
        ),
        migrations.CreateModel(
            name="CircleMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("moderator", "Moderator"),
                            ("admin", "Admin"),
                        ],
                        default="member",
                        max_length=50,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="circles.circle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circle_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "circle_memberships",
            },
        ),
        migrations.AddIndex(
            model_name="circle",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=["is_active"],
                name="idx_circles_active",
            ),
        ),
        migrations.AddIndex(
            model_name="circle",
            index=models.Index(fields=["-created_at"], name="idx_circles_created"),
        ),
        migrations.AddIndex(
            model_name="circlemembership",
            index=models.Index(fields=["circle"], name="idx_memberships_circle"),
        ),
        migrations.AddIndex(
            model_name="circlemembership",
            index=models.Index(fields=["user"], name="idx_memberships_user"),
        ),
        migrations.AddIndex(
            model_name="circlemembership",
            index=models.Index(fields=["circle", "user"], name="idx_memberships_composite"),
        ),
        migrations.AddConstraint(
            model_name="circlemembership",
            constraint=models.UniqueConstraint(
                fields=("circle", "user"), name="unique_circle_user_membership"
            ),
        ),
    ]
