# Generated by Django 5.0.1 on 2026-03-16 20:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Anchor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "anchor_type",
                    models.CharField(
                        choices=[
                            ("bible_verse", "Bible Verse"),
                            ("devotional", "Devotional"),
                            ("image", "Image"),
                            ("video", "Video"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                ("scripture_book", models.CharField(blank=True, max_length=100)),
                ("scripture_chapter", models.IntegerField(blank=True, null=True)),
                ("scripture_verse_start", models.IntegerField(blank=True, null=True)),
                ("scripture_verse_end", models.IntegerField(blank=True, null=True)),
                ("scripture_version", models.CharField(blank=True, default="KJV", max_length=20)),
                ("scripture_text", models.TextField(blank=True)),
                ("media_url", models.URLField(blank=True, max_length=500)),
                ("published_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("is_notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anchors",
                        to="circles.circle",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_anchors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "anchors",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="AnchorPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("page_number", models.IntegerField()),
                ("title", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField()),
                ("media_url", models.URLField(blank=True, max_length=500)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="circles.anchor",
                    ),
                ),
            ],
            options={
                "db_table": "anchor_pages",
                "ordering": ["page_number"],
            },
        ),
        migrations.AddIndex(
            model_name="anchor",
            index=models.Index(
                fields=["circle", "-published_at"], name="idx_anchors_circle_published"
            ),
        ),
        migrations.AddIndex(
            model_name="anchor",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=["circle", "expires_at"],
                name="idx_anchors_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="anchorpage",
            constraint=models.UniqueConstraint(
                fields=("anchor", "page_number"), name="unique_anchor_page_number"
            ),
        ),
    ]
