# Generated by Django 5.0.1 on 2026-03-28 01:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0002_anchor_anchorpage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnchorResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("reflection", "Reflection"),
                            ("prayer", "Prayer"),
                            ("question", "Question"),
                            ("reply", "Reply"),
                        ],
                        default="reflection",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("media_url", models.URLField(blank=True, max_length=500)),
                (
                    "media_type",
                    models.CharField(
                        blank=True, choices=[("image", "Image"), ("video", "Video")], max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("reaction_count", models.IntegerField(default=0)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="circles.anchor",
                    ),
                ),
                (
                    "parent_response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="circles.anchorresponse",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anchor_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "anchor_responses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnchorResponseReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("amen", "Amen"),
                            ("encouraged", "Encouraged"),
                            ("thoughtful", "Thoughtful"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="circles.anchorresponse",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anchor_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "anchor_response_reactions",
            },
        ),
        migrations.CreateModel(
            name="CircleReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("anchor", "Anchor"),
                            ("response", "Anchor Response"),
                            ("circle", "Circle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_id", models.UUIDField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("resolved_kept", "Resolved - Kept"),
                            ("resolved_removed", "Resolved - Removed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="circles.circle",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "circle_reports",
            },
        ),
        migrations.AddIndex(
            model_name="anchorresponse",
            index=models.Index(
                fields=["anchor", "-created_at"], name="idx_responses_anchor_created"
            ),
        ),
        migrations.AddIndex(
            model_name="anchorresponse",
            index=models.Index(fields=["user"], name="idx_responses_user"),
        ),
        migrations.AddIndex(
            model_name="anchorresponse",
            index=models.Index(
                fields=["parent_response", "-created_at"], name="idx_responses_parent"
            ),
        ),
        migrations.AddIndex(
            model_name="anchorresponsereaction",
            index=models.Index(fields=["response"], name="idx_reactions_response"),
        ),
        migrations.AddIndex(
            model_name="anchorresponsereaction",
            index=models.Index(fields=["user"], name="idx_reactions_user"),
        ),
        migrations.AddConstraint(
            model_name="anchorresponsereaction",
            constraint=models.UniqueConstraint(
                fields=("response", "user"), name="unique_response_user_reaction"
            ),
        ),
        migrations.AddIndex(
            model_name="circlereport",
            index=models.Index(fields=["circle", "status"], name="idx_reports_circle_status"),
        ),
        migrations.AddIndex(
            model_name="circlereport",
            index=models.Index(fields=["target_type", "target_id"], name="idx_reports_target"),
        ),
        migrations.AddConstraint(
            model_name="circlereport",
            constraint=models.UniqueConstraint(
                fields=("reporter", "target_type", "target_id"), name="unique_reporter_target"
            ),
        ),
    ]
