# Generated by Django 5.0.1 on 2026-04-07 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0004_rename_scripture_version_to_translation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="anchor",
            name="anchor_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("posted", "Posted"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="posted",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="anchor",
            name="celery_task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="anchor",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="anchor",
            name="preview_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="anchor",
            name="scheduled_for",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="anchor",
            name="style_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="circle",
            name="last_edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="circle",
            name="profile_image_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="circle",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="anchor",
            index=models.Index(
                condition=models.Q(("anchor_status", "scheduled")),
                fields=["scheduled_for"],
                name="idx_anchors_scheduled",
            ),
        ),
    ]
