# Generated by Django 5.0.1 on 2026-05-07 11:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0005_anchor_anchor_status_anchor_celery_task_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="anchor",
            name="anchor_image",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="anchor",
            name="anchor_image_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="anchor",
            name="anchor_liked_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="anchor",
            name="anchor_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="anchor",
            name="anchor_thumbnail",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="anchor",
            name="anchor_verse",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="anchor",
            name="anchor_video",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="anchor",
            name="background_colors",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="anchor",
            name="background_image",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="anchor",
            name="prayed_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="circle",
            name="banner_image",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.CreateModel(
            name="CirclePost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("image_url", models.URLField(blank=True, default="", max_length=500)),
                ("media_url", models.URLField(blank=True, default="", max_length=500)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("prayed_count", models.PositiveIntegerField(default=0)),
                ("anchor_liked_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="circles.circle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circle_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "circle_posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CirclePostEngagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to="circles.circlepost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circle_post_engagements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "circle_post_engagements",
            },
        ),
        migrations.CreateModel(
            name="AnchorEngagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "engagement_type",
                    models.CharField(choices=[("pray", "Pray"), ("like", "Like")], max_length=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to="circles.anchor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anchor_engagements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "anchor_engagements",
                "indexes": [
                    models.Index(
                        fields=["anchor", "engagement_type"], name="idx_anchor_engagements_type"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="anchorengagement",
            constraint=models.UniqueConstraint(
                fields=("anchor", "user", "engagement_type"), name="unique_anchor_user_engagement"
            ),
        ),
        migrations.AddIndex(
            model_name="circlepost",
            index=models.Index(fields=["circle", "-created_at"], name="idx_cposts_circle_created"),
        ),
        migrations.AddIndex(
            model_name="circlepost",
            index=models.Index(fields=["user"], name="idx_circle_posts_user"),
        ),
        migrations.AddIndex(
            model_name="circlepostengagement",
            index=models.Index(fields=["post"], name="idx_cpost_engage_post"),
        ),
        migrations.AddConstraint(
            model_name="circlepostengagement",
            constraint=models.UniqueConstraint(
                fields=("post", "user"), name="unique_circle_post_user_pray"
            ),
        ),
    ]
