# Generated by Django 5.0.1 on 2026-05-08 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0006_mobile_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="circlerule",
            name="circle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="circles.circle",
            ),
        ),
        migrations.AlterField(
            model_name="anchor",
            name="anchor_type",
            field=models.CharField(
                choices=[
                    ("bible_verse", "Bible Verse"),
                    ("devotional", "Devotional"),
                    ("text", "Text"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("image_text", "Image Text"),
                ],
                max_length=20,
            ),
        ),
    ]
