# Generated by Django 5.0.1 on 2026-05-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0007_circlerule_circle_alter_anchor_anchor_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="circle",
            name="display_member_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
