# Generated by Django 5.0.1 on 2026-05-14 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0008_circle_display_member_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="circlepostengagement",
            name="unique_circle_post_user_pray",
        ),
        migrations.RemoveIndex(
            model_name="circlepostengagement",
            name="idx_cpost_engage_post",
        ),
        migrations.AddField(
            model_name="circlepostengagement",
            name="engagement_type",
            field=models.CharField(
                choices=[("pray", "Pray"), ("like", "Like")], default="pray", max_length=10
            ),
        ),
        migrations.AddIndex(
            model_name="circlepostengagement",
            index=models.Index(fields=["post", "engagement_type"], name="idx_cpost_engage_type"),
        ),
        migrations.AddIndex(
            model_name="circlepostengagement",
            index=models.Index(fields=["user"], name="idx_cpost_engage_user"),
        ),
        migrations.AddConstraint(
            model_name="circlepostengagement",
            constraint=models.UniqueConstraint(
                fields=("post", "user", "engagement_type"),
                name="unique_circle_post_user_engagement",
            ),
        ),
    ]
