# Generated by Django 5.0.1 on 2026-05-18 19:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0009_mobile_circle_post_engagement_fix"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CirclePostComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.TextField()),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="circles.circlepost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circle_post_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "circle_post_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CirclePostCommentLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="circles.circlepostcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circle_comment_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "circle_post_comment_likes",
            },
        ),
        migrations.AddIndex(
            model_name="circlepostcomment",
            index=models.Index(fields=["post", "created_at"], name="idx_cpcomments_post_dt"),
        ),
        migrations.AddIndex(
            model_name="circlepostcomment",
            index=models.Index(fields=["user"], name="idx_cpcomments_user"),
        ),
        migrations.AddIndex(
            model_name="circlepostcommentlike",
            index=models.Index(fields=["comment"], name="idx_cpcomment_likes_comment"),
        ),
        migrations.AddIndex(
            model_name="circlepostcommentlike",
            index=models.Index(fields=["user"], name="idx_cpcomment_likes_user"),
        ),
        migrations.AddConstraint(
            model_name="circlepostcommentlike",
            constraint=models.UniqueConstraint(
                fields=("comment", "user"), name="unique_circle_comment_like"
            ),
        ),
    ]
