# Generated by Django 5.2.15 on 2026-07-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0013_hiddencirclecontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circlereport",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("anchor", "Anchor"),
                    ("response", "Anchor Response"),
                    ("circle", "Circle"),
                    ("post", "Circle Post"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="hiddencirclecontent",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("anchor", "Anchor"),
                    ("response", "Anchor Response"),
                    ("circle", "Circle"),
                    ("post", "Circle Post"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
