# Generated by Django 5.2.17 on 2026-09-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0016_alter_circlereport_target_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="circlepost",
            name="anchor_background_colors",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="circlepost",
            name="anchor_background_image",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="circlepost",
            name="anchor_bible_reference",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="circlepost",
            name="anchor_bible_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="circlepost",
            name="anchor_content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="circlepost",
            name="anchor_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="circlepost",
            name="anchor_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="circlepost",
            name="anchor_media_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="circlepost",
            name="anchor_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="circlepost",
            name="anchor_type",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
