# Generated by Django 5.0.1 on 2026-03-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="reason",
            field=models.CharField(
                choices=[
                    ("disrespectful_to_faith", "Disrespectful to Christ/church"),
                    ("misuse_scripture", "Misuse of scripture/unbiblical doctrine"),
                    ("attacking_church", "Attacking a church, leader, or group"),
                    ("scam", "Scam or fraud"),
                    ("hate_speech", "Hate speech or discrimination"),
                    ("policy_violation", "Restricted or against policy content"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
