# Generated by Django 5.0.1 on 2026-04-07 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engagement", "0002_remove_bookmarkfolder_icon"),
        ("moderation", "0002_alter_report_reason"),
        ("posts", "0004_rename_scripture_version_to_translation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="report",
            name="ck_report_has_target",
        ),
        migrations.AddField(
            model_name="report",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dismiss", "Dismiss"),
                    ("hide_content", "Hide Content"),
                    ("warn_user", "Warn User"),
                    ("delete_content", "Delete Content"),
                    ("delete_and_warn", "Delete and Warn"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="internal_notes",
            field=models.TextField(
                blank=True, default="", help_text="Admin-only notes. Never visible to end users."
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="target_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="target_type",
            field=models.CharField(
                choices=[("post", "Post"), ("comment", "Comment"), ("profile", "Profile")],
                db_index=True,
                default="post",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["target_type", "target_id"], name="idx_report_target"),
        ),
    ]
