# Generated by Django 5.2.15 on 2026-07-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderation", "0004_report_set_null_unique_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dismiss", "Dismiss"),
                    ("hide_content", "Hide Content"),
                    ("warn_user", "Warn User"),
                    ("delete_content", "Delete Content"),
                    ("delete_and_warn", "Delete and Warn"),
                    ("restore_content", "Restore Content"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
