# Generated by Django 5.0.1 on 2026-03-20 23:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("platform", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "device_tokens",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("reply_comment", "Reply to Comment"),
                            ("reply_post", "Reply to Post"),
                            ("like_post", "Like Post"),
                            ("like_comment", "Like Comment"),
                            ("new_anchor", "New Anchor"),
                            ("mention", "Mention"),
                            ("new_circle_post", "New Circle Post"),
                            ("admin_announcement", "Admin Announcement"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                ("reference_type", models.CharField(blank=True, max_length=50)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("deleted", "Deleted")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("anchor_notifications", models.BooleanField(default=True)),
                ("reply_notifications", models.BooleanField(default=True)),
                ("like_notifications", models.BooleanField(default=True)),
                ("circle_activity_notifications", models.BooleanField(default=True)),
                ("admin_announcements", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_preferences",
            },
        ),
        migrations.AddConstraint(
            model_name="devicetoken",
            constraint=models.UniqueConstraint(fields=("user", "token"), name="unique_user_token"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"], name="idx_notif_user_read_dt"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["reference_type", "reference_id"], name="idx_notif_ref"),
        ),
    ]
