# Generated by Django 5.0.1 on 2026-03-20 23:55

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("reply_comment", "Reply to Comment"),
                            ("reply_post", "Reply to Post"),
                            ("like_post", "Like Post"),
                            ("like_comment", "Like Comment"),
                            ("new_anchor", "New Anchor"),
                            ("mention", "Mention"),
                            ("new_circle_post", "New Circle Post"),
                            ("admin_announcement", "Admin Announcement"),
                        ],
                        max_length=50,
                    ),
                ),
                ("sent_count", models.IntegerField(default=0)),
                ("opened_count", models.IntegerField(default=0)),
                ("user_return_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "notification_metrics",
            },
        ),
        migrations.AddConstraint(
            model_name="notificationmetrics",
            constraint=models.UniqueConstraint(
                fields=("date", "notification_type"), name="unique_date_type_metrics"
            ),
        ),
    ]
