# Generated by Django 5.0.1 on 2026-05-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_notificationmetrics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="digest_sent",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="digest_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="digest_email_enabled",
            field=models.BooleanField(
                default=True, help_text="Whether to receive the daily notification digest email."
            ),
        ),
    ]
