# Generated by Django 5.0.1 on 2026-04-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BibleTranslation",
            fields=[
                ("code", models.CharField(max_length=20, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("language", models.CharField(default="en", max_length=10)),
                ("source", models.CharField(default="jsdelivr", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("verse_count", models.IntegerField(default=0)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "scripture_translations",
            },
        ),
        migrations.CreateModel(
            name="ScriptureBook",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "testament",
                    models.CharField(
                        choices=[("OT", "Old Testament"), ("NT", "New Testament")], max_length=2
                    ),
                ),
                ("chapters", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "scripture_books",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="BibleVerse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("translation", models.CharField(db_index=True, max_length=20)),
                ("book_id", models.IntegerField(db_index=True)),
                ("chapter", models.IntegerField(db_index=True)),
                ("verse", models.IntegerField(db_index=True)),
                ("text", models.TextField()),
                ("book_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "scripture_verses",
                "indexes": [
                    models.Index(
                        fields=["translation", "book_id", "chapter", "verse"],
                        name="idx_verse_primary_lookup",
                    ),
                    models.Index(fields=["book_id", "chapter"], name="idx_verse_book_chapter"),
                    models.Index(fields=["translation", "book_id"], name="idx_verse_trans_book"),
                ],
                "unique_together": {("translation", "book_id", "chapter", "verse")},
            },
        ),
    ]
